- name: variable from promt
  hosts: localhost
  vars_prompt:

  - name: USERNAME
    prompt: please enter your username
    private: false

  - name: PASSWORD
    prompt: please enter your password
    private: false
  
  tasks:
    - name: print a massege
      ansible.builtin.debug:
        msg: "username:{{USERNAME}},password:{{PASSWORD}}"


